# fly.toml app configuration file generated for emp-management on 2023-05-01T18:29:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "emp-management"
primary_region = "ams"

[build]
  image = "mcarnecer/employeemanagementapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "547398278354931"
  CloudinarySettings__CloudName = "daiu0ybh2"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
